{% set name = "lfric_reader" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/niwa/lfric_reader/archive/v{{ version }}.tar.gz
  sha256: 4033dbd4b6e7db393144de6a77637d52652745a532b2edf1bbc8ce251ee9713e

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make  # [unix]
    - cmake
  host:
    - paraview
    - vtk
    - python
    - pip
    - setuptools_scm
    - qt-main
    - libxslt
    - libxml2-devel
    - zlib
    - libpng
    - vulkan-headers
  run:
    - paraview
    - python
    - netcdf4

test:
  commands:
    - python -c "import paraview.simple as pvs; pvs.LoadPlugin('$PREFIX/lib/netCDFLFRicReader/netCDFLFRicReader.so')"  # [not win]
    - python -c "import paraview.simple as pvs; pvs.LoadPlugin(r'%PREFIX%\Library\bin\netCDFLFRicReader\netCDFLFRicReader.dll')"  # [win]
    - replace_ugrid_metadata -h

about:
  home: https://github.com/niwa/lfric_reader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ParaView plugin that reads output from the LFRic code in netCDF UGRID format
  description: |
    ParaView plugin that reads output from the LFRic
    code in netCDF UGRID format.
  doc_url: https://github.com/niwa/lfric_reader
  dev_url: https://github.com/niwa/lfric_reader

extra:
  recipe-maintainers:
    - tinyendian
